# Here, you can upgrade your layouts and views to AssetHat. For example, find
# this sort of code in your app:
#
#     stylesheet_link_tag 'reset', 'application'
#     javascript_include_tag(
#       Rails.env.production? ? '<Google CDN URL>' : 'jquery-1.6.1')
#     javascript_include_tag 'utilities', 'application'
#
# Create matching bundles in this file (no `.css` or `.js` suffixes needed;
# ERb is supported if you need it):
#
#     css:
#       bundles:
#         application:
#           - reset
#           - application
#     js:
#       vendors:
#         jquery:
#           version: 1.6.1
#       bundles:
#         application:
#           - utilities
#           - application
#
# Then, simplify your layouts and views to match your bundles:
#
#     include_css :bundle => 'application'
#     include_js  :jquery, :bundle => 'application'
#
# This makes it really easy to reuse sets of CSS/JS files across layouts.
#
# Lastly, set up your deployment script to run `rake asset_hat:minify`
# automatically. This creates minified versions of your CSS/JS; your original
# code is untouched. If you deploy with Capistrano, here's an example recipe:
# https://github.com/mintdigital/asset_hat/blob/master/lib/asset_hat/capistrano.rb
#
# That's it! In development, individual CSS/JS files are loaded separately,
# and your local copy of jQuery is used. In production, your minified CSS/JS
# bundles are loaded, and jQuery is loaded from Google's CDN.
#
# More info: https://github.com/mintdigital/asset_hat/#readme

css:
  engine: cssmin
  # Available minification engines:
  # http://mintdigital.github.com/asset_hat/doc/classes/AssetHat/CSS/Engines.html

  bundles:
    css-bundle-1:
      - css-file-1-1
      - css-file-1-2
      - css-file-1-3
    css-bundle-2:
      - css-file-2-1
      - css-file-2-2
      - css-file-2-3

js:
  engine: jsmin
  # Available minification engines:
  # http://mintdigital.github.com/asset_hat/doc/classes/AssetHat/JS/Engines.html

  # Enable if you're using jQuery or other popular JS:
  #
  # vendors:
  #   jquery:
  #     version: 1.6.1
  #
  # Supported vendors:
  # http://mintdigital.github.com/asset_hat/doc/classes/AssetHat/JS/Vendors.html

  bundles:
    js-bundle-1:
      - js-file-1-1
      - js-file-1-2
      - js-file-1-3
    js-bundle-2:
      - js-file-2-1
      - js-file-2-2
      - js-file-2-3
